name: Testing

on: [push]

jobs:
    build-latest:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build LTS
              uses: actions/setup-node@v2
              with:
                  node-version: 14.x
            - run: yarn install --frozen-lockfile
            - run: yarn global add typescript
            - run: tsc
            - name: Upload artifacts LTS
              uses: actions/upload-artifact@v2
              with:
                  path: node_modules/
